//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Life
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coords
    {
        public int Id { get; set; }
        public int CoordX { get; set; }
        public int CoordY { get; set; }
        public int TypeLiving { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
