//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Life_Console.GameService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameImage", Namespace="http://schemas.datacontract.org/2004/07/LifeService")]
    [System.SerializableAttribute()]
    public partial class GameImage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IterationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SaveIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Iteration {
            get {
                return this.IterationField;
            }
            set {
                if ((this.IterationField.Equals(value) != true)) {
                    this.IterationField = value;
                    this.RaisePropertyChanged("Iteration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SaveId {
            get {
                return this.SaveIdField;
            }
            set {
                if ((this.SaveIdField.Equals(value) != true)) {
                    this.SaveIdField = value;
                    this.RaisePropertyChanged("SaveId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SizeX {
            get {
                return this.SizeXField;
            }
            set {
                if ((this.SizeXField.Equals(value) != true)) {
                    this.SizeXField = value;
                    this.RaisePropertyChanged("SizeX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SizeY {
            get {
                return this.SizeYField;
            }
            set {
                if ((this.SizeYField.Equals(value) != true)) {
                    this.SizeYField = value;
                    this.RaisePropertyChanged("SizeY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameService.ILifeService")]
    public interface ILifeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILifeService/Save", ReplyAction="http://tempuri.org/ILifeService/SaveResponse")]
        bool Save(Life_Console.GameService.GameImage gameImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILifeService/Save", ReplyAction="http://tempuri.org/ILifeService/SaveResponse")]
        System.Threading.Tasks.Task<bool> SaveAsync(Life_Console.GameService.GameImage gameImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILifeService/GetStudentById", ReplyAction="http://tempuri.org/ILifeService/GetStudentByIdResponse")]
        BLL.SaveService GetStudentById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILifeService/GetStudentById", ReplyAction="http://tempuri.org/ILifeService/GetStudentByIdResponse")]
        System.Threading.Tasks.Task<BLL.SaveService> GetStudentByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILifeService/GetAllSave", ReplyAction="http://tempuri.org/ILifeService/GetAllSaveResponse")]
        BLL.SaveService[] GetAllSave();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILifeService/GetAllSave", ReplyAction="http://tempuri.org/ILifeService/GetAllSaveResponse")]
        System.Threading.Tasks.Task<BLL.SaveService[]> GetAllSaveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILifeService/StartNewGame", ReplyAction="http://tempuri.org/ILifeService/StartNewGameResponse")]
        void StartNewGame(int type, Life.Initialization.Options newOptions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILifeService/StartNewGame", ReplyAction="http://tempuri.org/ILifeService/StartNewGameResponse")]
        System.Threading.Tasks.Task StartNewGameAsync(int type, Life.Initialization.Options newOptions);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILifeServiceChannel : Life_Console.GameService.ILifeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LifeServiceClient : System.ServiceModel.ClientBase<Life_Console.GameService.ILifeService>, Life_Console.GameService.ILifeService {
        
        public LifeServiceClient() {
        }
        
        public LifeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LifeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LifeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LifeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Save(Life_Console.GameService.GameImage gameImage) {
            return base.Channel.Save(gameImage);
        }
        
        public System.Threading.Tasks.Task<bool> SaveAsync(Life_Console.GameService.GameImage gameImage) {
            return base.Channel.SaveAsync(gameImage);
        }
        
        public BLL.SaveService GetStudentById(int id) {
            return base.Channel.GetStudentById(id);
        }
        
        public System.Threading.Tasks.Task<BLL.SaveService> GetStudentByIdAsync(int id) {
            return base.Channel.GetStudentByIdAsync(id);
        }
        
        public BLL.SaveService[] GetAllSave() {
            return base.Channel.GetAllSave();
        }
        
        public System.Threading.Tasks.Task<BLL.SaveService[]> GetAllSaveAsync() {
            return base.Channel.GetAllSaveAsync();
        }
        
        public void StartNewGame(int type, Life.Initialization.Options newOptions) {
            base.Channel.StartNewGame(type, newOptions);
        }
        
        public System.Threading.Tasks.Task StartNewGameAsync(int type, Life.Initialization.Options newOptions) {
            return base.Channel.StartNewGameAsync(type, newOptions);
        }
    }
}
